name: climate_proj
channels:
  - conda-forge
  - defaults
dependencies:
  - arrow=1.4.0=pyhcf101f3_0
  - blas=2.138=openblas
  - blas-devel=3.9.0=38_h11c0a38_openblas
  - blinker=1.9.0=pyhff2d567_0
  - bottleneck=1.4.2=py311h03d0aa3_1
  - brotli-python=1.2.0=py311h5b255a4_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.11.4=hca03da5_0
  - certifi=2025.11.12=py311hca03da5_0
  - cffi=2.0.0=py311h73c2a22_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - click=8.3.0=pyh707e725_0
  - codecarbon=2.2.2=pyh1a96a4e_0
  - dash=3.2.0=pyhd8ed1ab_0
  - dash-bootstrap-components=2.0.4=pyhcf101f3_0
  - dash-core-components=2.0.0=pyhd8ed1ab_1
  - dash-html-components=2.0.0=pyhd8ed1ab_2
  - dash-table=5.0.0=pyhd8ed1ab_1
  - et_xmlfile=2.0.0=py311hca03da5_0
  - expat=2.7.3=h982b769_0
  - fire=0.7.1=pyhd8ed1ab_0
  - flask=3.1.2=pyhd8ed1ab_0
  - fuzzywuzzy=0.18.0=pyhd8ed1ab_1
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - itsdangerous=2.2.0=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - levenshtein=0.27.1=py311hee39554_0
  - libblas=3.9.0=38_h51639a9_openblas
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=20.1.8=hd7fd590_1
  - libffi=3.4.4=hca03da5_1
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblapacke=3.9.0=38_h1b118fd_openblas
  - libopenblas=0.3.30=openmp_ha158390_3
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.5=h4a912ad_0
  - markupsafe=3.0.3=pyh7db6752_0
  - narwhals=2.11.0=pyhcf101f3_0
  - ncurses=6.5=hee39554_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.14.1=py311h5fbe615_0
  - numpy=2.3.4=py311h4bb6f22_1
  - numpy-base=2.3.4=py311h23175f9_1
  - nvidia-ml-py=13.580.82=pyhd8ed1ab_0
  - openblas=0.3.30=openmp_hea878ba_3
  - openpyxl=3.1.5=py311h80987f9_0
  - openssl=3.6.0=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311h3f644e9_1
  - pip=25.2=pyhc872135_1
  - plotly=6.4.0=pyhd8ed1ab_0
  - psutil=7.0.0=py311haa24f5a_1
  - py-cpuinfo=9.0.0=pyhd8ed1ab_1
  - pycparser=2.22=pyh29332c3_1
  - pynvml=13.0.1=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.14=hf701271_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-levenshtein=0.27.1=pyhff2d567_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - pytz=2025.2=pyhd8ed1ab_0
  - rapidfuzz=3.14.1=py311h0962b89_0
  - readline=8.3=h0b18652_0
  - requests=2.32.5=py311hca03da5_1
  - retrying=1.4.2=pyhe01879c_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.51.0=hab6afd1_0
  - termcolor=3.2.0=pyhd8ed1ab_0
  - tk=8.6.15=hcd8a7d5_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - werkzeug=3.1.3=pyhd8ed1ab_1
  - wheel=0.45.1=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.24.0=py311hbc14757_0
  - zstd=1.5.7=h6491c7d_2
prefix: /Users/lizziehealy/miniconda3/envs/climate_proj
